import Link from "next/link";
import { ToolSeoContent } from "@/components/seo/tool-seo-content";
import type { FaqItem } from "@/components/seo/faq-section";

export const JSON_TOOL_FAQS: FaqItem[] = [
  {
    question: "Does this JSON formatter send my data to a server?",
    answer:
      "No. Parsing, formatting, validating, and repairing all happen locally in your browser using a bundled Monaco editor and JSON engine. Nothing you paste is ever uploaded, logged, or stored remotely.",
  },
  {
    question: "Can it fix invalid JSON automatically?",
    answer:
      "Yes. The \"Fix it\" button runs an auto-repair pass that handles common mistakes — trailing commas, single-quoted strings, unquoted keys, missing commas, and comments — and shows you a diff before applying the fix.",
  },
  {
    question: "What's the difference between formatting and minifying?",
    answer:
      "Formatting re-indents JSON with consistent spacing so it's easy to read. Minifying strips all non-essential whitespace to produce the smallest possible payload, which is useful before sending JSON over the network.",
  },
  {
    question: "Can I search inside deeply nested JSON?",
    answer:
      "Yes. The search box matches keys, values, or both, and each result shows the exact path to that node plus its line and column so you can jump straight to it in the editor.",
  },
  {
    question: "Is there a file size limit?",
    answer:
      "Because everything runs client-side, the only real limit is your browser's available memory — there's no server-side upload cap to worry about.",
  },
];

export function JsonSeoContent() {
  return (
    <ToolSeoContent
      aboutTitle="What is a JSON formatter and validator?"
      about={
        <>
          <p>
            <strong>JSON (JavaScript Object Notation)</strong> is the standard format for exchanging data between
            APIs, config files, and frontend/backend services. A JSON formatter takes minified or messy JSON and
            re-indents it into a readable structure, while a validator checks the text against the JSON
            specification and points out exactly where it breaks — a missing comma, an unescaped quote, a trailing
            comma after the last array item, and so on.
          </p>
          <p>
            This tool combines both, plus an auto-repair engine for the errors that show up most often when JSON
            gets pasted from logs, hand-edited, or generated by another language.
          </p>
        </>
      }
      howToTitle="How to format and validate JSON online"
      howTo={
        <ol className="list-decimal space-y-2 pl-5">
          <li>Paste or type your JSON into the editor on the left.</li>
          <li>
            Errors appear inline and in the Results panel with the exact line and column — click any error to jump
            to it.
          </li>
          <li>
            Use <strong>Format</strong> to pretty-print, <strong>Minify</strong> to compress, or{" "}
            <strong>Sort keys</strong> to normalize key order for diffing.
          </li>
          <li>
            If the JSON won&apos;t parse at all, click <strong>Fix it</strong> to auto-repair common syntax mistakes.
          </li>
          <li>
            Decoding a Base64 string in the <Link href="/base64">Base64 tool</Link> that turns out to be JSON? It
            shows up there already formatted in an embedded copy of this same editor.
          </li>
        </ol>
      }
      faqItems={JSON_TOOL_FAQS}
    />
  );
}
